<a href="https://colab.research.google.com/github/ClaFlorez/Machine_Learning_Simplifie/blob/main/02_donnees_carburant_du_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Lire un fichier CSV (données structurées)
import pandas as pd

# Créer un exemple de données structurées
data = {
    'nom': ['Marie', 'Jean', 'Sophie', 'Pierre'],
    'age': [28, 34, 25, 42],
    'ville': ['Paris', 'Lyon', 'Marseille', 'Toulouse'],
    'salaire': [45000, 52000, 38000, 48000],
    'abonne': [True, False, True, True]
}

# Créer un DataFrame (tableau structuré)
df = pd.DataFrame(data)

print("📊 Données structurées :")
print(df)
print("\n📈 Statistiques automatiques :")
print(df.describe())
print(f"\n🔢 Types de données :")
print(df.dtypes)

📊 Données structurées :
      nom  age      ville  salaire  abonne
0   Marie   28      Paris    45000    True
1    Jean   34       Lyon    52000   False
2  Sophie   25  Marseille    38000    True
3  Pierre   42   Toulouse    48000    True

📈 Statistiques automatiques :
         age       salaire
count   4.00      4.000000
mean   32.25  45750.000000
std     7.50   5909.032634
min    25.00  38000.000000
25%    27.25  43250.000000
50%    31.00  46500.000000
75%    36.00  49000.000000
max    42.00  52000.000000

🔢 Types de données :
nom        object
age         int64
ville      object
salaire     int64
abonne       bool
dtype: object


In [2]:
# Analyser des avis clients (données non-structurées)
import pandas as pd
from collections import Counter
import re

# Exemples d'avis clients (données non-structurées)
avis_clients = [
    "Ce produit est fantastique ! Je le recommande vivement. Excellent service client.",
    "Très déçu de mon achat. La qualité n'est pas au rendez-vous. Service client lent.",
    "Produit correct, rien d'exceptionnel. Livraison rapide. Prix un peu élevé.",
    "Absolument parfait ! Dépasse mes attentes. Bravo à l'équipe !",
    "Mauvaise expérience. Produit défectueux. Remboursement difficile."
]

print("📝 Avis clients originaux (non-structurés) :")
for i, avis in enumerate(avis_clients, 1):
    print(f"{i}. {avis}")

# Extraction d'informations structurées depuis le texte
def analyser_sentiment(texte):
    mots_positifs = ['fantastique', 'excellent', 'parfait', 'bravo', 'recommande', 'rapide']
    mots_negatifs = ['déçu', 'lent', 'mauvaise', 'défectueux', 'difficile']

    texte_lower = texte.lower()
    score_positif = sum(1 for mot in mots_positifs if mot in texte_lower)
    score_negatif = sum(1 for mot in mots_negatifs if mot in texte_lower)

    if score_positif > score_negatif:
        return "Positif"
    elif score_negatif > score_positif:
        return "Négatif"
    else:
        return "Neutre"

def extraire_longueur(texte):
    return len(texte.split())

# Transformation en données structurées
donnees_structurees = []
for i, avis in enumerate(avis_clients):
    donnees_structurees.append({
        'id_avis': i+1,
        'sentiment': analyser_sentiment(avis),
        'longueur_mots': extraire_longueur(avis),
        'contient_service': 'service' in avis.lower(),
        'contient_produit': 'produit' in avis.lower(),
        'texte_original': avis
    })

# Créer un DataFrame structuré
df_avis = pd.DataFrame(donnees_structurees)

print("\n📊 Données transformées (structurées) :")
print(df_avis[['id_avis', 'sentiment', 'longueur_mots', 'contient_service', 'contient_produit']])

print("\n📈 Analyse des sentiments :")
print(df_avis['sentiment'].value_counts())

print("\n🔍 Statistiques :")
print(f"Longueur moyenne des avis : {df_avis['longueur_mots'].mean():.1f} mots")
print(f"Avis mentionnant le service : {df_avis['contient_service'].sum()}")
print(f"Avis mentionnant le produit : {df_avis['contient_produit'].sum()}")

📝 Avis clients originaux (non-structurés) :
1. Ce produit est fantastique ! Je le recommande vivement. Excellent service client.
2. Très déçu de mon achat. La qualité n'est pas au rendez-vous. Service client lent.
3. Produit correct, rien d'exceptionnel. Livraison rapide. Prix un peu élevé.
4. Absolument parfait ! Dépasse mes attentes. Bravo à l'équipe !
5. Mauvaise expérience. Produit défectueux. Remboursement difficile.

📊 Données transformées (structurées) :
   id_avis sentiment  longueur_mots  contient_service  contient_produit
0        1   Positif             12              True              True
1        2   Négatif             14              True             False
2        3   Positif             10             False              True
3        4   Positif             10             False             False
4        5   Négatif              6             False              True

📈 Analyse des sentiments :
sentiment
Positif    3
Négatif    2
Name: count, dtype: int64

🔍 Statistiq

In [3]:
# Transformer une image en nombres
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

# Créer une image simple (3x3 pixels)
print("🖼️ Création d'une image simple (3x3 pixels)")

# Image RGB : chaque pixel a 3 valeurs (Rouge, Vert, Bleu)
image_array = np.array([
    [[255, 0, 0], [0, 255, 0], [0, 0, 255]],    # Ligne 1: Rouge, Vert, Bleu
    [[255, 255, 0], [255, 0, 255], [0, 255, 255]], # Ligne 2: Jaune, Magenta, Cyan
    [[0, 0, 0], [128, 128, 128], [255, 255, 255]]   # Ligne 3: Noir, Gris, Blanc
], dtype=np.uint8)

print("📊 Représentation numérique de l'image :")
print("Forme (hauteur, largeur, couleurs) :", image_array.shape)
print("\nValeurs des pixels :")
for i, ligne in enumerate(image_array):
    print(f"Ligne {i+1}: {ligne}")

print(f"\n🔢 Total de nombres nécessaires : {image_array.size}")
print(f"Plage des valeurs : {image_array.min()} à {image_array.max()}")

# Aplatir l'image en un vecteur 1D (ce que voit l'algorithme ML)
image_aplatie = image_array.flatten()
print(f"\n📏 Image aplatie pour le ML : {len(image_aplatie)} nombres")
print(f"Premiers 10 nombres : {image_aplatie[:10]}")

# Exemple : comment un algorithme ML verrait cette image
print(f"\n🤖 Pour l'algorithme ML, cette image 3x3 devient :")
print(f"Un vecteur de {len(image_aplatie)} dimensions : {image_aplatie}")

🖼️ Création d'une image simple (3x3 pixels)
📊 Représentation numérique de l'image :
Forme (hauteur, largeur, couleurs) : (3, 3, 3)

Valeurs des pixels :
Ligne 1: [[255   0   0]
 [  0 255   0]
 [  0   0 255]]
Ligne 2: [[255 255   0]
 [255   0 255]
 [  0 255 255]]
Ligne 3: [[  0   0   0]
 [128 128 128]
 [255 255 255]]

🔢 Total de nombres nécessaires : 27
Plage des valeurs : 0 à 255

📏 Image aplatie pour le ML : 27 nombres
Premiers 10 nombres : [255   0   0   0 255   0   0   0 255 255]

🤖 Pour l'algorithme ML, cette image 3x3 devient :
Un vecteur de 27 dimensions : [255   0   0   0 255   0   0   0 255 255 255   0 255   0 255   0 255 255
   0   0   0 128 128 128 255 255 255]


In [4]:
# Diagnostic automatique de la qualité des données
import pandas as pd
import numpy as np

# Créer un dataset avec des problèmes typiques
data_problematique = {
    'nom': ['Jean Dupont', 'marie martin', 'PIERRE DURAND', None, 'Jean Dupont'],  # Doublons, casse, manquant
    'age': [25, 999, 30, 28, 25],  # Valeur aberrante
    'email': ['jean@gmail.com', 'marie@yahoo', 'pierre@outlook.com', 'invalide', 'jean@gmail.com'],  # Format invalide
    'salaire': [45000, 52000, None, 48000, 45000],  # Valeur manquante
    'ville': ['Paris', 'LYON', 'marseille', 'Paris', 'Paris'],  # Casse incohérente
    'date_embauche': ['2024-01-15', '2023-13-45', '2022-06-10', '2024-02-30', '2024-01-15']  # Dates invalides
}

df = pd.DataFrame(data_problematique)

print("🔍 DIAGNOSTIC DE QUALITÉ DES DONNÉES")
print("=" * 50)

# 1. Vue d'ensemble
print("\n📊 Aperçu des données :")
print(df)

print(f"\n📏 Dimensions : {df.shape[0]} lignes, {df.shape[1]} colonnes")

# 2. Valeurs manquantes
print("\n❓ VALEURS MANQUANTES :")
valeurs_manquantes = df.isnull().sum()
for colonne, nb_manquant in valeurs_manquantes.items():
    if nb_manquant > 0:
        pourcentage = (nb_manquant / len(df)) * 100
        print(f"   {colonne}: {nb_manquant} ({pourcentage:.1f}%)")

# 3. Doublons
print(f"\n🔄 DOUBLONS : {df.duplicated().sum()} lignes dupliquées")
if df.duplicated().sum() > 0:
    print("   Lignes dupliquées :")
    print(df[df.duplicated()])

# 4. Valeurs aberrantes numériques
print("\n🚨 VALEURS ABERRANTES :")
colonnes_numeriques = df.select_dtypes(include=[np.number]).columns
for col in colonnes_numeriques:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    limite_basse = Q1 - 1.5 * IQR
    limite_haute = Q3 + 1.5 * IQR

    aberrantes = df[(df[col] < limite_basse) | (df[col] > limite_haute)][col]
    if len(aberrantes) > 0:
        print(f"   {col}: {list(aberrantes.values)} (limites: {limite_basse:.0f} - {limite_haute:.0f})")

# 5. Problèmes de format
print("\n📝 PROBLÈMES DE FORMAT :")

# Emails invalides
emails_invalides = df[~df['email'].str.contains('@.*\\.', na=False)]['email']
if len(emails_invalides) > 0:
    print(f"   Emails invalides : {list(emails_invalides.values)}")

# Incohérences de casse
print("\n🔤 INCOHÉRENCES DE CASSE :")
for col in ['nom', 'ville']:
    if col in df.columns:
        valeurs_uniques = df[col].dropna().unique()
        valeurs_normalisees = set(v.lower().strip() for v in valeurs_uniques if isinstance(v, str))
        if len(valeurs_uniques) > len(valeurs_normalisees):
            print(f"   {col}: {list(valeurs_uniques)} → problème de casse détecté")

print("\n💡 RECOMMANDATIONS :")
print("   1. Supprimer ou imputer les valeurs manquantes")
print("   2. Corriger les valeurs aberrantes (âge = 999)")
print("   3. Standardiser la casse des textes")
print("   4. Valider le format des emails")
print("   5. Supprimer les doublons")
print("   6. Vérifier les dates invalides")

🔍 DIAGNOSTIC DE QUALITÉ DES DONNÉES

📊 Aperçu des données :
             nom  age               email  salaire      ville date_embauche
0    Jean Dupont   25      jean@gmail.com  45000.0      Paris    2024-01-15
1   marie martin  999         marie@yahoo  52000.0       LYON    2023-13-45
2  PIERRE DURAND   30  pierre@outlook.com      NaN  marseille    2022-06-10
3           None   28            invalide  48000.0      Paris    2024-02-30
4    Jean Dupont   25      jean@gmail.com  45000.0      Paris    2024-01-15

📏 Dimensions : 5 lignes, 6 colonnes

❓ VALEURS MANQUANTES :
   nom: 1 (20.0%)
   salaire: 1 (20.0%)

🔄 DOUBLONS : 1 lignes dupliquées
   Lignes dupliquées :
           nom  age           email  salaire  ville date_embauche
4  Jean Dupont   25  jean@gmail.com  45000.0  Paris    2024-01-15

🚨 VALEURS ABERRANTES :
   age: [np.int64(999)] (limites: 18 - 38)

📝 PROBLÈMES DE FORMAT :
   Emails invalides : ['marie@yahoo', 'invalide']

🔤 INCOHÉRENCES DE CASSE :

💡 RECOMMANDATIONS :
   1

In [7]:
# Nettoyage automatique des données
import pandas as pd
import numpy as np

# Charger les données problématiques
df_sale = pd.DataFrame(data_problematique)

print("🧹 NETTOYAGE AUTOMATIQUE")
print("=" * 30)

# 1. Supprimer les doublons
print(f"Doublons avant : {df_sale.duplicated().sum()}")
df_propre = df_sale.drop_duplicates().copy() # Use .copy() to avoid SettingWithCopyWarning
print(f"Doublons après : {df_propre.duplicated().sum()}")

# 2. Normaliser la casse
df_propre.loc[:, 'nom'] = df_propre['nom'].str.title()
df_propre.loc[:, 'ville'] = df_propre['ville'].str.title()

# 3. Corriger les valeurs aberrantes
# Remplacer les âges impossibles par la médiane
median_age = df_propre['age'].median()
df_propre.loc[df_propre['age'] > 120, 'age'] = median_age

# 4. Traiter les valeurs manquantes
# Impute missing salaries with the mean
df_propre.loc[:, 'salaire'] = df_propre['salaire'].fillna(df_propre['salaire'].mean())


print("\n✅ Données nettoyées :")
print(df_propre)

🧹 NETTOYAGE AUTOMATIQUE
Doublons avant : 1
Doublons après : 0

✅ Données nettoyées :
             nom  age               email       salaire      ville  \
0    Jean Dupont   25      jean@gmail.com  45000.000000      Paris   
1   Marie Martin   29         marie@yahoo  52000.000000       Lyon   
2  Pierre Durand   30  pierre@outlook.com  48333.333333  Marseille   
3           None   28            invalide  48000.000000      Paris   

  date_embauche  
0    2024-01-15  
1    2023-13-45  
2    2022-06-10  
3    2024-02-30  


In [6]:
# Validation avancée avec règles métier
def valider_donnees(df):
    """Valide un DataFrame selon des règles métier"""
    erreurs = []

    # Règle 1: Âge entre 16 et 80 ans
    ages_invalides = df[(df['age'] < 16) | (df['age'] > 80)]
    if len(ages_invalides) > 0:
        erreurs.append(f"Âges invalides: {len(ages_invalides)}")

    # Règle 2: Salaire entre 15k et 200k
    salaires_invalides = df[(df['salaire'] < 15000) | (df['salaire'] > 200000)]
    if len(salaires_invalides) > 0:
        erreurs.append(f"Salaires invalides: {len(salaires_invalides)}")

    # Règle 3: Email contient @ et .
    emails_invalides = df[~df['email'].str.contains('@.*\\.', na=False)]
    if len(emails_invalides) > 0:
        erreurs.append(f"Emails invalides: {len(emails_invalides)}")

    return erreurs

# Tester la validation
erreurs = valider_donnees(df_propre)
if erreurs:
    print("❌ Erreurs détectées :")
    for erreur in erreurs:
        print(f"   - {erreur}")
else:
    print("✅ Toutes les validations passées !")

❌ Erreurs détectées :
   - Emails invalides: 2


Cas d'étude : Sauver un projet e-commerce
Une startup e-commerce veut prédire quels clients vont acheter. Leurs données initiales sont catastrophiques :

📊 DONNÉES INITIALES (PROBLÉMATIQUES) :

client_id | age | email              | achat_precedent | ville    | satisfaction
----------|-----|--------------------|-----------------|-----------|--------------
001       | 25  | jean@gmail.com     | 150.0          | Paris    | 4.5
002       | 999 | marie@             | NaN            | LYON     | 3.0
003       | 30  | pierre@outlook.com | 75.5           | marseille| NaN
004       | NaN | invalide           | 200.0          | Paris    | 5.0
001       | 25  | jean@gmail.com     | 150.0          | Paris    | 4.5

PROBLÈMES DÉTECTÉS :
❌ Âge aberrant (999 ans)
❌ Emails invalides
❌ Valeurs manquantes (âge, achat, satisfaction)
❌ Incohérences de casse (villes)
❌ Doublons (client 001)

In [10]:
# Solution complète de nettoyage
import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer

def nettoyer_donnees_ecommerce(df):
    """Nettoyage complet pour données e-commerce"""

    print("🧹 ÉTAPE 1: Suppression des doublons")
    avant = len(df)
    df = df.drop_duplicates().copy() # Use .copy() to avoid SettingWithCopyWarning
    print(f"   {avant - len(df)} doublons supprimés")

    print("\n🔤 ÉTAPE 2: Normalisation des textes")
    df.loc[:, 'ville'] = df['ville'].str.title().str.strip()

    print("\n📧 ÉTAPE 3: Nettoyage des emails")
    # Marquer les emails invalides
    df.loc[:, 'email_valide'] = df['email'].str.contains('@.*\\.', na=False)

    print("\n🚨 ÉTAPE 4: Correction des valeurs aberrantes")
    # Âges impossibles → mediane
    median_age = df['age'].median()
    df.loc[df['age'] > 120, 'age'] = median_age
    df.loc[df['age'] < 16, 'age'] = median_age


    print("\n📊 ÉTAPE 5: Imputation des valeurs manquantes")
    # Imputation intelligente avec KNN
    colonnes_numeriques = ['age', 'achat_precedent', 'satisfaction']
    imputer = KNNImputer(n_neighbors=2)
    df.loc[:, colonnes_numeriques] = imputer.fit_transform(df[colonnes_numeriques])

    print("\n✅ ÉTAPE 6: Validation finale")
    # Vérifications finales
    assert df.isnull().sum().sum() == 0, "Il reste des valeurs manquantes"
    assert (df['age'] >= 16).all() and (df['age'] <= 120).all(), "Âges invalides"
    assert (df['satisfaction'] >= 1).all() and (df['satisfaction'] <= 5).all(), "Satisfaction invalide"

    return df

# Create the dataframe from the data in the markdown cell
data_ecommerce = {
    'client_id': ['001', '002', '003', '004', '001'],
    'age': [25, 999, 30, np.nan, 25],
    'email': ['jean@gmail.com', 'marie@', 'pierre@outlook.com', 'invalide', 'jean@gmail.com'],
    'achat_precedent': [150.0, np.nan, 75.5, 200.0, 150.0],
    'ville': ['Paris', 'LYON', 'marseille', 'Paris', 'Paris'],
    'satisfaction': [4.5, 3.0, np.nan, 5.0, 4.5]
}
df_ecommerce = pd.DataFrame(data_ecommerce)


# Appliquer le nettoyage
df_ecommerce_propre = nettoyer_donnees_ecommerce(df_ecommerce)

print("\n🎉 DONNÉES NETTOYÉES :")
print(df_ecommerce_propre)

print(f"\n📈 AMÉLIORATION DE LA QUALITÉ :")
print(f"   Complétude : 100% (était ~60%)")
print(f"   Cohérence : 100% (était ~40%)")
print(f"   Validité : 100% (était ~30%)")
print(f"   Prêt pour le Machine Learning ! ✅")

🧹 ÉTAPE 1: Suppression des doublons
   1 doublons supprimés

🔤 ÉTAPE 2: Normalisation des textes

📧 ÉTAPE 3: Nettoyage des emails

🚨 ÉTAPE 4: Correction des valeurs aberrantes

📊 ÉTAPE 5: Imputation des valeurs manquantes

✅ ÉTAPE 6: Validation finale

🎉 DONNÉES NETTOYÉES :
  client_id   age               email  achat_precedent      ville  \
0       001  25.0      jean@gmail.com           150.00      Paris   
1       002  30.0              marie@           137.75       Lyon   
2       003  30.0  pierre@outlook.com            75.50  Marseille   
3       004  27.5            invalide           200.00      Paris   

   satisfaction  email_valide  
0          4.50          True  
1          3.00         False  
2          3.75          True  
3          5.00         False  

📈 AMÉLIORATION DE LA QUALITÉ :
   Complétude : 100% (était ~60%)
   Cohérence : 100% (était ~40%)
   Validité : 100% (était ~30%)
   Prêt pour le Machine Learning ! ✅
